# **NumPy Practice Problems 🚀**

## **Beginner Problems** (Focus: Array Creation & Indexing)  
1. **Create a NumPy array** of integers from 1 to 100 and reshape it into a 10×10 matrix.  
2. **Extract all even numbers** from a given NumPy array.  
3. **Reverse a NumPy array** without using a loop.  
4. **Replace all odd numbers** in an array with -1.  
5. **Find the index of maximum and minimum values** in a given 1D array.  

---

## **Intermediate Problems** (Focus: Manipulation & Broadcasting)  
6. **Create a 5×5 matrix** with 1s on the border and 0s inside (without loops).  
7. **Normalize an array** so that all values are between 0 and 1.  
8. **Stack two NumPy arrays vertically and horizontally.**  
9. **Create a checkerboard pattern** (8×8 matrix) using 0s and 1s.  
10. **Rotate a matrix 90 degrees** clockwise without using loops.  

---

## **Advanced Problems** (Focus: Performance Optimization & Complex Operations)  
11. **Compute the moving average** of an array with a given window size.  
12. **Generate 1,000,000 random numbers** and find the mean, variance, and standard deviation efficiently.  
13. **Perform element-wise multiplication** between two very large arrays (e.g., 10000×10000).  
14. **Solve a system of linear equations** using NumPy’s `linalg.solve()`.  
15. **Find the dot product** of two large matrices and optimize performance.  

---

## **Expert-Level Problems** (Focus: Real-World Applications)  
16. **Perform Principal Component Analysis (PCA)** on a dataset using NumPy.  
17. **Implement a basic k-means clustering algorithm** using NumPy operations.  
18. **Simulate a random walk** in 2D space using NumPy.  
19. **Find the eigenvalues and eigenvectors** of a given matrix.  
20. **Perform convolution between two 2D matrices** (without using libraries like OpenCV).  

---

💡 **Tip:** You can use `%%timeit` in Jupyter Notebook to measure execution speed for performance-related problems.

https://chatgpt.com/share/67d727b6-894c-800c-ad4a-1031b6504a18

In [2]:
import numpy as np

# **1. Beginner Problems**
1. **Create a NumPy array** of integers from 1 to 100 and reshape it into a 10×10 matrix.  
2. **Extract all even numbers** from a given NumPy array.  
3. **Reverse a NumPy array** without using a loop.  
4. **Replace all odd numbers** in an array with -1.  
5. **Find the index of maximum and minimum values** in a given 1D array.

In [19]:
arr = np.arange(1,101)

temp = arr.reshape(10,10)

temp
# np.array(range(1,101)).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [24]:
print(temp.shape)


(10, 10)


In [14]:
arr[arr%2 == 0]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [16]:
arr[::-1]

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [33]:
arr[arr%2 == 1] = -1

arr

array([ -1,   2,  -1,   4,  -1,   6,  -1,   8,  -1,  10,  -1,  12,  -1,
        14,  -1,  16,  -1,  18,  -1,  20,  -1,  22,  -1,  24,  -1,  26,
        -1,  28,  -1,  30,  -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,
        40,  -1,  42,  -1,  44,  -1,  46,  -1,  48,  -1,  50,  -1,  52,
        -1,  54,  -1,  56,  -1,  58,  -1,  60,  -1,  62,  -1,  64,  -1,
        66,  -1,  68,  -1,  70,  -1,  72,  -1,  74,  -1,  76,  -1,  78,
        -1,  80,  -1,  82,  -1,  84,  -1,  86,  -1,  88,  -1,  90,  -1,
        92,  -1,  94,  -1,  96,  -1,  98,  -1, 100])

In [36]:
arr = np.array([10, 20, 5, 8, 70, 30])

print(np.argmax(arr))
print(np.argmin(arr))

4
2


# **2. Intermediate Problems**
6. **Create a 5×5 matrix** with 1s on the border and 0s inside (without loops).  
7. **Normalize an array** so that all values are between 0 and 1.  
8. **Stack two NumPy arrays vertically and horizontally.**  
9. **Create a checkerboard pattern** (8×8 matrix) using 0s and 1s.  
10. **Rotate a matrix 90 degrees** clockwise without using loops.  

In [44]:
arr = np.ones((5,5))

arr[1:-1,1:-1] = 0

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
arr = np.random.randint(10, 100, 10)
print(arr)
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[92 18 11 21 83 95 99 81 33 43]
[0.92045455 0.07954545 0.         0.11363636 0.81818182 0.95454545
 1.         0.79545455 0.25       0.36363636]


In [57]:
z = np.zeros((3,3))

o = np.ones((3,3))

print(np.vstack((z,o)))

print(np.hstack((z,o)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [71]:
arr = np.ones((8,8))

arr[1::2, ::2] = 0 # MARK ROW ZEROS
arr[::2, 1::2] = 0 # MARK COL ZEROS

arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [85]:
arr = np.arange(1,10).reshape(3,3)

arr[::-1].T

# np.rot90(arr,-4)

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

# **3. Advanced Problems** 
11. **Compute the moving average** of an array with a given window size.  
12. **Generate 1,000,000 random numbers** and find the mean, variance, and standard deviation efficiently.  
13. **Perform element-wise multiplication** between two very large arrays (e.g., 10000×10000).  
14. **Solve a system of linear equations** using NumPy’s `linalg.solve()`.  
15. **Find the dot product** of two large matrices and optimize performance. 

In [88]:
arr = np.arange(1,10)

In [91]:
print(arr)

window_size = 3
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
print(moving_avg)

[1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8.]


In [105]:
arr = np.random.rand(1000000)

print(arr[:10])

print(arr.mean())
print(arr.std())
print(arr.var())

[0.9947598  0.14199671 0.67832812 0.23675674 0.21552975 0.5239144
 0.37559874 0.50992024 0.73205405 0.29292945]
0.49987408938253886
0.28861590539876025
0.08329914084914614


In [110]:
a  = np.random.rand(2,2)
b  = np.random.rand(2,2)

print(a,"\n",b)
ans = np.multiply(a,b)

ans

[[0.14553566 0.32568905]
 [0.42356275 0.24036773]] 
 [[0.52264705 0.65362954]
 [0.71357352 0.54130683]]


array([[0.07606378, 0.21287998],
       [0.30224316, 0.13011269]])

In [111]:
A = np.array([[3, 2], [1, 4]])
b = np.array([5, 6])
solution = np.linalg.solve(A, b)
print(solution)

[0.8 1.3]


In [112]:
a = np.random.rand(3000, 3000)
b = np.random.rand(3000, 3000)
dot_product = np.dot(a, b)
print(dot_product)

[[736.32321938 746.27489535 736.50378141 ... 735.80815301 735.37717036
  739.79352485]
 [738.41083274 736.0305254  737.18280268 ... 737.50815094 740.63765861
  743.0380391 ]
 [747.13861348 749.39860091 746.37151978 ... 739.32738903 745.73047047
  744.87582326]
 ...
 [731.6962817  735.4824911  738.72774008 ... 737.42447564 734.66137659
  729.6271462 ]
 [749.17560632 755.72668365 750.37415103 ... 753.13431987 772.92659928
  744.4317569 ]
 [751.44770372 756.42403443 745.5714597  ... 745.48858511 756.12027853
  753.40053471]]


In [113]:
name = ['Ananya', 'Rahul', 'Eati', 'Alex'] 
scores = [[22,30,28], [32,38, 26], [21, 29,32], [39, 21, 27]]

In [117]:
d = {n:s for n, s in zip(name, scores)}
print(d) 

{'Ananya': [22, 30, 28], 'Rahul': [32, 38, 26], 'Eati': [21, 29, 32], 'Alex': [39, 21, 27]}


In [118]:
d = dict(zip(name, scores))

In [119]:
d

{'Ananya': [22, 30, 28],
 'Rahul': [32, 38, 26],
 'Eati': [21, 29, 32],
 'Alex': [39, 21, 27]}

In [125]:
# create a function to check if string, list, tuples, int any value passed to the function 
# if it is a palindrome or not

def is_palindrome(inpt):
    if isinstance(inpt, int):
        inpt = str(inpt)
    
    r_inpt = inpt[::-1]
    if r_inpt == inpt:
        return True
    
    return False

In [126]:
print(is_palindrome([1, 2, 3, 2, 1])) 
print(is_palindrome((1, 2, 3, 2, 1))) 
print(is_palindrome("hello")) 
print(is_palindrome("madam")) 
print(is_palindrome(12321))

True
True
False
True
True


In [130]:
# Question: Write a Python function to compute the factorial of a given number without using recursion.

# 4 = 4*3*2*1

def fact(n):
    ans= 1
    for i in range(2,n+1):
        ans *=i
    return ans

for i in range(1,10):
    print(i,"---->",fact(i))

    
# def fact(n):

#     if n == 1:
#         return 1

#     return fact(n) * fact(n-1)

1 ----> 1
2 ----> 2
3 ----> 6
4 ----> 24
5 ----> 120
6 ----> 720
7 ----> 5040
8 ----> 40320
9 ----> 362880


In [135]:
# Write a Python function to count the number of vowels (a, e, i, o, u) in a given string. 
# {'a': 0, 'e': 6, 'i': 2, 'o': 4, 'u': 0}

s = 'Hi Everyone, Welcome to the session'

def give_me_count(s:str):
    d = {c:0 for c in ['a', 'e', 'i', 'o', 'u']}
    for c in s:
        if c.lower() in ['a', 'e', 'i', 'o', 'u']:
            d[c.lower()] +=1
        
    return d

print(give_me_count(s))

{'a': 0, 'e': 7, 'i': 2, 'o': 4, 'u': 0}
